#!/bin/sh

version=$1

is_ruby_version_installed () {
  if [[ `rbenv versions` == *$1* ]]; then
    return 0
  else
    return 1
  fi
}

is_ruby_version_installed $version

if [[ $? -eq 1 ]]; then
  rbenv install $version
fi

rbenv global $version
