#!/bin/sh

# Manages a git repository.
#
# If the repository does not exist, it will be cloned. If it already exists, it
# will be updated via `git pull`.
#
# $1: clone path
# $2: repository URL

is_git_repository () {
  if [[ -d "$1/.git" ]]; then
    return 0
  else
    return 1
  fi
}

if is_git_repository $1; then
  (cd $1 && git pull)
else
  # Allow cloning into existing directories
  name=$(mktemp -u)

  if [[ -d $1 ]]; then
    mv $1 $name
  fi

  git clone $2 $1

  if [[ -d $name ]]; then
    cp -r $name/* $1
    rm -r $name
  fi
fi
