(source org)
(source gnu)
(source melpa)

;; Package configuration
(depends-on "use-package")

;; Libaries
(depends-on "dash")
(depends-on "s")

;; Planning
(depends-on "org-plus-contrib")
(depends-on "org-bullets")

;; Load PATH from shell, even when emacs is not started from one
(depends-on "exec-path-from-shell")

;; General editing
(depends-on "avy")
(depends-on "ace-window")
(depends-on "multiple-cursors")
(depends-on "smartparens")
(depends-on "expand-region")
(depends-on "wrap-region")
(depends-on "centimacro")
(depends-on "move-text")
(depends-on "visual-regexp")
(depends-on "key-chord")
(depends-on "hydra")

;; Convenience
(depends-on "dictcc")

;; UI
(depends-on "color-theme")
(depends-on "material-theme")
(depends-on "smart-mode-line")
(depends-on "rainbow-delimiters")
(depends-on "shackle")
(depends-on "rainbow-mode")
(depends-on "color-identifiers-mode")
(depends-on "highlight-symbol")
(depends-on "discover-my-major")

;; Snippets
(depends-on "yasnippet")

;; Autocomplete
(depends-on "company")

;; VCS
(depends-on "magit")
(depends-on "git-timemachine")

;; Syntax checking
(depends-on "flycheck")

;; Searching
(depends-on "ag")
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "flx-ido")

;; Markdown
(depends-on "markdown-mode")

;; Emacs Lisp
(depends-on "macrostep")

;; Haskell
(depends-on "haskell-mode")
(depends-on "shm")
(depends-on "ghc")
(depends-on "ghci-completion")

;; Clojure
(depends-on "clojure-mode")
(depends-on "cider")

;; Python
(depends-on "py-yapf")
(depends-on "pyenv-mode")
(depends-on "anaconda-mode")
(depends-on "company-anaconda")

;; Ruby
(depends-on "robe")
(depends-on "inf-ruby")
(depends-on "rspec-mode")
(depends-on "yard-mode")

;; Web development
(depends-on "web-mode")

;; HTML replacements
(depends-on "haml-mode")

;; CSS replacements
(depends-on "scss-mode")
(depends-on "less-css-mode")

;; Javascript
(depends-on "js2-mode")
(depends-on "js2-refactor")

;; Javascript replacements
(depends-on "coffee-mode")

;; YAML
(depends-on "yaml-mode")

;; LaTeX
(depends-on "auctex")
