(source gnu)
(source melpa)

;; Libaries
(depends-on "dash")
(depends-on "s")

;; General editing
(depends-on "evil")
(depends-on "ace-jump-mode")
(depends-on "key-chord")
(depends-on "multiple-cursors")
(depends-on "smartparens")
(depends-on "expand-region")
(depends-on "wrap-region")

;; UI
(depends-on "color-theme")
(depends-on "smart-mode-line")

;; Snippets
(depends-on "yasnippet")

;; Autocomplete
(depends-on "auto-complete")
(depends-on "ac-nrepl")
(depends-on "ac-math")
(depends-on "company")

;; VCS
(depends-on "magit")

;; Searching
(depends-on "ag")
(depends-on "projectile")
(depends-on "flx-ido")

;; Markdown
(depends-on "markdown-mode")

;; Clojure
(depends-on "clojure-mode")
(depends-on "clojure-test-mode")
(depends-on "cider")
(depends-on "rainbow-delimiters")

;; Ruby
(depends-on "robe")
(depends-on "company-inf-ruby")
(depends-on "rspec-mode")

;; HTML replacements
(depends-on "haml-mode")
(depends-on "jade-mode")

;; CSS replacements
(depends-on "scss-mode")
(depends-on "less-css-mode")

;; Javascript replacements
(depends-on "coffee-mode")

;; LaTeX
(depends-on "auctex")
