(source org)
(source gnu)
(source melpa)

;; Libaries
(depends-on "dash")
(depends-on "s")

;; Planning
(depends-on "org-plus-contrib")

;; Loading project specific settings
(depends-on "editorconfig")

;; General editing
(depends-on "ace-jump-mode")
(depends-on "ace-window")
(depends-on "multiple-cursors")
(depends-on "smartparens")
(depends-on "expand-region")
(depends-on "wrap-region")
(depends-on "centimacro")
(depends-on "move-text")

;; UI
(depends-on "sublime-themes")
(depends-on "zenburn-theme")
(depends-on "smart-mode-line")
(depends-on "rainbow-delimiters")
(depends-on "smex")
(depends-on "popwin")
(depends-on "rainbow-mode")
(depends-on "golden-ratio")
(depends-on "color-identifiers-mode")

;; Snippets
(depends-on "yasnippet")

;; Autocomplete
(depends-on "company")
(depends-on "company-cider")

;; VCS
(depends-on "magit")

;; Searching
(depends-on "ag")
(depends-on "helm")
(depends-on "projectile")
(depends-on "helm-projectile")
(depends-on "flx-ido")

;; Markdown
(depends-on "markdown-mode")

;; Haskell
(depends-on "haskell-mode")

;; Clojure
(depends-on "clojure-mode")
(depends-on "clojure-test-mode")
(depends-on "cider")

;; Ruby
(depends-on "robe")
(depends-on "company-inf-ruby")
(depends-on "rspec-mode")
(depends-on "yard-mode")

;; HTML replacements
(depends-on "haml-mode")
(depends-on "jade-mode")

;; CSS replacements
(depends-on "scss-mode")
(depends-on "less-css-mode")

;; Javascript
(depends-on "js2-mode")
(depends-on "js2-refactor")

;; Javascript replacements
(depends-on "coffee-mode")

;; YAML
(depends-on "yaml-mode")

;; LaTeX
(depends-on "auctex")
