local wezterm = require "wezterm"
local act = wezterm.action
local config = wezterm.config_builder()

-- Appearance
config.color_scheme = "nord"
config.hide_tab_bar_if_only_one_tab = true
config.term = "xterm-24bit"

-- Disable win32 input mode to properly transfer C-M keys to emacs
--
-- https://github.com/wez/wezterm/issues/2196
config.allow_win32_input_mode = false

config.keys = {
   { key = "Tab", mods = "CTRL", action = act.ActivateTabRelative(1) },
   { key = "Tab", mods = "SHIFT|CTRL", action = act.ActivateTabRelative(-1) },
   { key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
   { key = "!", mods = "CTRL", action = act.ActivateTab(0) },
   { key = "!", mods = "SHIFT|CTRL", action = act.ActivateTab(0) },
   { key = "\"", mods = "ALT|CTRL", action = act.SplitVertical{ domain =  "CurrentPaneDomain" } },
   { key = "\"", mods = "SHIFT|ALT|CTRL", action = act.SplitVertical{ domain =  "CurrentPaneDomain" } },
   { key = "#", mods = "CTRL", action = act.ActivateTab(2) },
   { key = "#", mods = "SHIFT|CTRL", action = act.ActivateTab(2) },
   { key = "$", mods = "CTRL", action = act.ActivateTab(3) },
   { key = "$", mods = "SHIFT|CTRL", action = act.ActivateTab(3) },
   { key = "%", mods = "CTRL", action = act.ActivateTab(4) },
   { key = "%", mods = "SHIFT|CTRL", action = act.ActivateTab(4) },
   { key = "%", mods = "ALT|CTRL", action = act.SplitHorizontal{ domain =  "CurrentPaneDomain" } },
   { key = "%", mods = "SHIFT|ALT|CTRL", action = act.SplitHorizontal{ domain =  "CurrentPaneDomain" } },
   { key = "&", mods = "CTRL", action = act.ActivateTab(6) },
   { key = "&", mods = "SHIFT|CTRL", action = act.ActivateTab(6) },
   { key = "\"", mods = "SHIFT|ALT|CTRL", action = act.SplitVertical{ domain =  "CurrentPaneDomain" } },
   { key = "(", mods = "CTRL", action = act.ActivateTab(-1) },
   { key = "(", mods = "SHIFT|CTRL", action = act.ActivateTab(-1) },
   { key = ")", mods = "CTRL", action = act.ResetFontSize },
   { key = ")", mods = "SHIFT|CTRL", action = act.ResetFontSize },
   { key = "*", mods = "CTRL", action = act.ActivateTab(7) },
   { key = "*", mods = "SHIFT|CTRL", action = act.ActivateTab(7) },
   { key = "+", mods = "CTRL", action = act.IncreaseFontSize },
   { key = "+", mods = "SHIFT|CTRL", action = act.IncreaseFontSize },
   { key = "-", mods = "CTRL", action = act.DecreaseFontSize },
   { key = "-", mods = "SHIFT|CTRL", action = act.DecreaseFontSize },
   { key = "-", mods = "SUPER", action = act.DecreaseFontSize },
   { key = "0", mods = "CTRL", action = act.ResetFontSize },
   { key = "0", mods = "SHIFT|CTRL", action = act.ResetFontSize },
   { key = "0", mods = "SUPER", action = act.ResetFontSize },
   { key = "1", mods = "SHIFT|CTRL", action = act.ActivateTab(0) },
   { key = "1", mods = "SUPER", action = act.ActivateTab(0) },
   { key = "2", mods = "SHIFT|CTRL", action = act.ActivateTab(1) },
   { key = "2", mods = "SUPER", action = act.ActivateTab(1) },
   { key = "3", mods = "SHIFT|CTRL", action = act.ActivateTab(2) },
   { key = "3", mods = "SUPER", action = act.ActivateTab(2) },
   { key = "4", mods = "SHIFT|CTRL", action = act.ActivateTab(3) },
   { key = "4", mods = "SUPER", action = act.ActivateTab(3) },
   { key = "5", mods = "SHIFT|CTRL", action = act.ActivateTab(4) },
   { key = "5", mods = "SHIFT|ALT|CTRL", action = act.SplitHorizontal{ domain =  "CurrentPaneDomain" } },
   { key = "5", mods = "SUPER", action = act.ActivateTab(4) },
   { key = "6", mods = "SHIFT|CTRL", action = act.ActivateTab(5) },
   { key = "6", mods = "SUPER", action = act.ActivateTab(5) },
   { key = "7", mods = "SHIFT|CTRL", action = act.ActivateTab(6) },
   { key = "7", mods = "SUPER", action = act.ActivateTab(6) },
   { key = "8", mods = "SHIFT|CTRL", action = act.ActivateTab(7) },
   { key = "8", mods = "SUPER", action = act.ActivateTab(7) },
   { key = "9", mods = "SHIFT|CTRL", action = act.ActivateTab(-1) },
   { key = "9", mods = "SUPER", action = act.ActivateTab(-1) },
   { key = "=", mods = "CTRL", action = act.IncreaseFontSize },
   { key = "=", mods = "SHIFT|CTRL", action = act.IncreaseFontSize },
   { key = "=", mods = "SUPER", action = act.IncreaseFontSize },
   { key = "@", mods = "CTRL", action = act.ActivateTab(1) },
   { key = "@", mods = "SHIFT|CTRL", action = act.ActivateTab(1) },
   { key = "C", mods = "CTRL", action = act.CopyTo "Clipboard" },
   { key = "C", mods = "SHIFT|CTRL", action = act.CopyTo "Clipboard" },
   { key = "F", mods = "CTRL", action = act.Search "CurrentSelectionOrEmptyString" },
   { key = "F", mods = "SHIFT|CTRL", action = act.Search "CurrentSelectionOrEmptyString" },
   { key = "K", mods = "CTRL", action = act.ClearScrollback "ScrollbackOnly" },
   { key = "K", mods = "SHIFT|CTRL", action = act.ClearScrollback "ScrollbackOnly" },
   { key = "L", mods = "CTRL", action = act.ShowDebugOverlay },
   { key = "L", mods = "SHIFT|CTRL", action = act.ShowDebugOverlay },
   { key = "M", mods = "CTRL", action = act.Hide },
   { key = "M", mods = "SHIFT|CTRL", action = act.Hide },
   { key = "R", mods = "CTRL", action = act.ReloadConfiguration },
   { key = "R", mods = "SHIFT|CTRL", action = act.ReloadConfiguration },
   { key = "T", mods = "CTRL", action = act.SpawnTab "CurrentPaneDomain" },
   { key = "T", mods = "SHIFT|CTRL", action = act.SpawnTab "CurrentPaneDomain" },
   { key = "U", mods = "CTRL", action = act.CharSelect{ copy_on_select = true, copy_to =  "ClipboardAndPrimarySelection" } },
   { key = "U", mods = "SHIFT|CTRL", action = act.CharSelect{ copy_on_select = true, copy_to =  "ClipboardAndPrimarySelection" } },
   { key = "V", mods = "CTRL", action = act.PasteFrom "Clipboard" },
   { key = "V", mods = "SHIFT|CTRL", action = act.PasteFrom "Clipboard" },
   { key = "W", mods = "CTRL", action = act.CloseCurrentTab{ confirm = false } },
   { key = "W", mods = "SHIFT|CTRL", action = act.CloseCurrentTab{ confirm = false } },
   { key = "X", mods = "CTRL", action = act.ActivateCopyMode },
   { key = "X", mods = "SHIFT|CTRL", action = act.ActivateCopyMode },
   { key = "Z", mods = "CTRL", action = act.TogglePaneZoomState },
   { key = "Z", mods = "SHIFT|CTRL", action = act.TogglePaneZoomState },
   { key = "[", mods = "SHIFT|SUPER", action = act.ActivateTabRelative(-1) },
   { key = "]", mods = "SHIFT|SUPER", action = act.ActivateTabRelative(1) },
   { key = "^", mods = "CTRL", action = act.ActivateTab(5) },
   { key = "^", mods = "SHIFT|CTRL", action = act.ActivateTab(5) },
   { key = "_", mods = "CTRL", action = act.DecreaseFontSize },
   { key = "_", mods = "SHIFT|CTRL", action = act.DecreaseFontSize },
   { key = "c", mods = "SHIFT|CTRL", action = act.CopyTo "Clipboard" },
   { key = "c", mods = "SUPER", action = act.CopyTo "Clipboard" },
   { key = "f", mods = "SHIFT|CTRL", action = act.Search "CurrentSelectionOrEmptyString" },
   { key = "f", mods = "SUPER", action = act.Search "CurrentSelectionOrEmptyString" },
   { key = "k", mods = "SHIFT|CTRL", action = act.ClearScrollback "ScrollbackOnly" },
   { key = "k", mods = "SUPER", action = act.ClearScrollback "ScrollbackOnly" },
   { key = "l", mods = "SHIFT|CTRL", action = act.ShowDebugOverlay },
   { key = "m", mods = "SHIFT|CTRL", action = act.Hide },
   { key = "m", mods = "SUPER", action = act.Hide },
   { key = "n", mods = "SUPER", action = act.SpawnWindow },
   { key = "r", mods = "SHIFT|CTRL", action = act.ReloadConfiguration },
   { key = "r", mods = "SUPER", action = act.ReloadConfiguration },
   { key = "t", mods = "SHIFT|CTRL", action = act.SpawnTab "CurrentPaneDomain" },
   { key = "t", mods = "SUPER", action = act.SpawnTab "CurrentPaneDomain" },
   { key = "u", mods = "SHIFT|CTRL", action = act.CharSelect{ copy_on_select = true, copy_to =  "ClipboardAndPrimarySelection" } },
   { key = "v", mods = "SHIFT|CTRL", action = act.PasteFrom "Clipboard" },
   { key = "v", mods = "SUPER", action = act.PasteFrom "Clipboard" },
   { key = "w", mods = "SHIFT|CTRL", action = act.CloseCurrentTab{ confirm = false } },
   { key = "w", mods = "SUPER", action = act.CloseCurrentTab{ confirm = false } },
   { key = "x", mods = "SHIFT|CTRL", action = act.ActivateCopyMode },
   { key = "z", mods = "SHIFT|CTRL", action = act.TogglePaneZoomState },
   { key = "{", mods = "SUPER", action = act.ActivateTabRelative(-1) },
   { key = "{", mods = "SHIFT|SUPER", action = act.ActivateTabRelative(-1) },
   { key = "}", mods = "SUPER", action = act.ActivateTabRelative(1) },
   { key = "}", mods = "SHIFT|SUPER", action = act.ActivateTabRelative(1) },
   { key = "phys:Space", mods = "SHIFT|CTRL", action = act.QuickSelect },
   { key = "PageUp", mods = "SHIFT", action = act.ScrollByPage(-1) },
   { key = "PageUp", mods = "CTRL", action = act.ActivateTabRelative(-1) },
   { key = "PageUp", mods = "SHIFT|CTRL", action = act.MoveTabRelative(-1) },
   { key = "PageDown", mods = "SHIFT", action = act.ScrollByPage(1) },
   { key = "PageDown", mods = "CTRL", action = act.ActivateTabRelative(1) },
   { key = "PageDown", mods = "SHIFT|CTRL", action = act.MoveTabRelative(1) },
   { key = "LeftArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection "Left" },
   { key = "LeftArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize{ "Left", 1 } },
   { key = "RightArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection "Right" },
   { key = "RightArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize{ "Right", 1 } },
   { key = "UpArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection "Up" },
   { key = "UpArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize{ "Up", 1 } },
   { key = "DownArrow", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection "Down" },
   { key = "DownArrow", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize{ "Down", 1 } },
   { key = "Insert", mods = "SHIFT", action = act.PasteFrom "PrimarySelection" },
   { key = "Insert", mods = "CTRL", action = act.CopyTo "PrimarySelection" },
   { key = "Copy", mods = "NONE", action = act.CopyTo "Clipboard" },
   { key = "Paste", mods = "NONE", action = act.PasteFrom "Clipboard" },

   -- from term-keys.el
   {key = "F1", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x61\x1f"}},
   {key = "F1", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x62\x1f"}},
   {key = "F1", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x63\x1f"}},
   {key = "F1", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x64\x1f"}},
   {key = "F1", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x65\x1f"}},
   {key = "F1", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x66\x1f"}},
   {key = "F1", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x67\x1f"}},
   {key = "F2", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x21\x41\x1f"}},
   {key = "F2", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x21\x42\x1f"}},
   {key = "F2", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x21\x43\x1f"}},
   {key = "F2", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x21\x44\x1f"}},
   {key = "F2", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x21\x45\x1f"}},
   {key = "F2", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x21\x46\x1f"}},
   {key = "F2", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x21\x47\x1f"}},
   {key = "F3", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x22\x21\x1f"}},
   {key = "F3", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x22\x22\x1f"}},
   {key = "F3", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x22\x23\x1f"}},
   {key = "F3", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x24\x1f"}},
   {key = "F3", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x25\x1f"}},
   {key = "F3", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x26\x1f"}},
   {key = "F3", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x27\x1f"}},
   {key = "F4", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x22\x61\x1f"}},
   {key = "F4", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x22\x62\x1f"}},
   {key = "F4", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x22\x63\x1f"}},
   {key = "F4", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x64\x1f"}},
   {key = "F4", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x65\x1f"}},
   {key = "F4", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x66\x1f"}},
   {key = "F4", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x22\x67\x1f"}},
   {key = "F5", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x23\x41\x1f"}},
   {key = "F5", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x23\x42\x1f"}},
   {key = "F5", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x23\x43\x1f"}},
   {key = "F5", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x23\x44\x1f"}},
   {key = "F5", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x23\x45\x1f"}},
   {key = "F5", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x23\x46\x1f"}},
   {key = "F5", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x23\x47\x1f"}},
   {key = "F6", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x24\x21\x1f"}},
   {key = "F6", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x24\x22\x1f"}},
   {key = "F6", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x24\x23\x1f"}},
   {key = "F6", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x24\x1f"}},
   {key = "F6", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x25\x1f"}},
   {key = "F6", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x26\x1f"}},
   {key = "F6", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x27\x1f"}},
   {key = "F7", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x24\x61\x1f"}},
   {key = "F7", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x24\x62\x1f"}},
   {key = "F7", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x24\x63\x1f"}},
   {key = "F7", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x64\x1f"}},
   {key = "F7", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x65\x1f"}},
   {key = "F7", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x66\x1f"}},
   {key = "F7", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x24\x67\x1f"}},
   {key = "F8", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x25\x41\x1f"}},
   {key = "F8", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x25\x42\x1f"}},
   {key = "F8", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x25\x43\x1f"}},
   {key = "F8", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x25\x44\x1f"}},
   {key = "F8", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x25\x45\x1f"}},
   {key = "F8", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x25\x46\x1f"}},
   {key = "F8", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x25\x47\x1f"}},
   {key = "F9", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x26\x21\x1f"}},
   {key = "F9", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x26\x22\x1f"}},
   {key = "F9", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x26\x23\x1f"}},
   {key = "F9", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x24\x1f"}},
   {key = "F9", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x25\x1f"}},
   {key = "F9", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x26\x1f"}},
   {key = "F9", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x27\x1f"}},
   {key = "F10", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x26\x61\x1f"}},
   {key = "F10", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x26\x62\x1f"}},
   {key = "F10", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x26\x63\x1f"}},
   {key = "F10", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x64\x1f"}},
   {key = "F10", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x65\x1f"}},
   {key = "F10", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x66\x1f"}},
   {key = "F10", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x26\x67\x1f"}},
   {key = "F11", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x27\x41\x1f"}},
   {key = "F11", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x27\x42\x1f"}},
   {key = "F11", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x27\x43\x1f"}},
   {key = "F11", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x27\x44\x1f"}},
   {key = "F11", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x27\x45\x1f"}},
   {key = "F11", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x27\x46\x1f"}},
   {key = "F11", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x27\x47\x1f"}},
   {key = "F12", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x28\x21\x1f"}},
   {key = "F12", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x28\x22\x1f"}},
   {key = "F12", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x28\x23\x1f"}},
   {key = "F12", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x28\x24\x1f"}},
   {key = "F12", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x28\x25\x1f"}},
   {key = "F12", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x28\x26\x1f"}},
   {key = "F12", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x28\x27\x1f"}},
   {key = "`", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2a\x62\x1f"}},
   {key = "`", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2a\x66\x1f"}},
   {key = "1", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2b\x42\x1f"}},
   {key = "1", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2b\x46\x1f"}},
   {key = "2", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x22\x1f"}},
   {key = "2", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x26\x1f"}},
   {key = "3", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x62\x1f"}},
   {key = "3", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x66\x1f"}},
   {key = "4", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2d\x42\x1f"}},
   {key = "4", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2d\x46\x1f"}},
   {key = "5", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x22\x1f"}},
   {key = "5", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x26\x1f"}},
   {key = "6", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x62\x1f"}},
   {key = "6", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x66\x1f"}},
   {key = "7", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2f\x42\x1f"}},
   {key = "7", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2f\x46\x1f"}},
   {key = "8", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x22\x1f"}},
   {key = "8", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x26\x1f"}},
   {key = "9", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x62\x1f"}},
   {key = "9", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x66\x1f"}},
   {key = "0", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x31\x42\x1f"}},
   {key = "0", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x31\x46\x1f"}},
   {key = "-", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x22\x1f"}},
   {key = "-", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x26\x1f"}},
   {key = "=", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x62\x1f"}},
   {key = "=", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x66\x1f"}},
   {key = "Backspace", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x33\x41\x1f"}},
   {key = "Backspace", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x33\x42\x1f"}},
   {key = "Backspace", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x33\x45\x1f"}},
   {key = "Backspace", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x33\x46\x1f"}},
   {key = "Tab", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x34\x22\x1f"}},
   {key = "Tab", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x26\x1f"}},
   {key = "Q", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x66\x1f"}},
   {key = "Q", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x67\x1f"}},
   {key = "W", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x35\x46\x1f"}},
   {key = "W", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x35\x47\x1f"}},
   {key = "E", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x26\x1f"}},
   {key = "E", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x27\x1f"}},
   {key = "R", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x66\x1f"}},
   {key = "R", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x67\x1f"}},
   {key = "T", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x37\x46\x1f"}},
   {key = "T", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x37\x47\x1f"}},
   {key = "Y", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x26\x1f"}},
   {key = "Y", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x27\x1f"}},
   {key = "U", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x66\x1f"}},
   {key = "U", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x67\x1f"}},
   {key = "I", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x39\x46\x1f"}},
   {key = "I", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x39\x47\x1f"}},
   {key = "O", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3a\x23\x1f"}},
   {key = "O", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x26\x1f"}},
   {key = "O", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x27\x1f"}},
   {key = "P", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3a\x63\x1f"}},
   {key = "P", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x66\x1f"}},
   {key = "P", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x67\x1f"}},
   {key = "[", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3b\x42\x1f"}},
   {key = "[", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3b\x46\x1f"}},
   {key = "]", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x22\x1f"}},
   {key = "]", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x26\x1f"}},
   {key = "Enter", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x3c\x61\x1f"}},
   {key = "Enter", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x62\x1f"}},
   {key = "Enter", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x65\x1f"}},
   {key = "Enter", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x66\x1f"}},
   {key = "A", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x26\x1f"}},
   {key = "A", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x27\x1f"}},
   {key = "S", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3e\x63\x1f"}},
   {key = "S", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x66\x1f"}},
   {key = "S", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x67\x1f"}},
   {key = "D", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x3f\x45\x1f"}},
   {key = "D", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3f\x46\x1f"}},
   {key = "D", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3f\x47\x1f"}},
   {key = "F", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x26\x1f"}},
   {key = "F", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x27\x1f"}},
   {key = "G", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x66\x1f"}},
   {key = "G", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x67\x1f"}},
   {key = "H", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x41\x46\x1f"}},
   {key = "H", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x41\x47\x1f"}},
   {key = "J", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x26\x1f"}},
   {key = "J", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x27\x1f"}},
   {key = "K", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x42\x63\x1f"}},
   {key = "K", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x66\x1f"}},
   {key = "K", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x67\x1f"}},
   {key = "L", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x43\x46\x1f"}},
   {key = "L", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x43\x47\x1f"}},
   {key = ";", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x22\x1f"}},
   {key = ";", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x26\x1f"}},
   {key = "'", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x62\x1f"}},
   {key = "'", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x66\x1f"}},
   {key = "\\", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x46\x22\x1f"}},
   {key = "\\", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x26\x1f"}},
   {key = "Z", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x66\x1f"}},
   {key = "Z", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x67\x1f"}},
   {key = "X", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x47\x46\x1f"}},
   {key = "X", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x47\x47\x1f"}},
   {key = "C", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x26\x1f"}},
   {key = "C", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x27\x1f"}},
   {key = "V", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x66\x1f"}},
   {key = "V", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x67\x1f"}},
   {key = "B", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x49\x46\x1f"}},
   {key = "B", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x49\x47\x1f"}},
   {key = "N", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4a\x23\x1f"}},
   {key = "N", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x26\x1f"}},
   {key = "N", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x27\x1f"}},
   {key = "M", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x66\x1f"}},
   {key = "M", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x67\x1f"}},
   {key = ",", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4b\x42\x1f"}},
   {key = ",", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4b\x46\x1f"}},
   {key = ".", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x22\x1f"}},
   {key = ".", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x26\x1f"}},
   {key = "/", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x62\x1f"}},
   {key = "/", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x66\x1f"}},
   {key = "Space", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x50\x22\x1f"}},
   {key = "Space", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x50\x26\x1f"}},
   {key = "Applications", mods = "", action = wezterm.action{SendString="\x1b\x1f\x52\x20\x1f"}},
   {key = "Applications", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x52\x21\x1f"}},
   {key = "Applications", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x52\x22\x1f"}},
   {key = "Applications", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x24\x1f"}},
   {key = "Applications", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x25\x1f"}},
   {key = "Applications", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x26\x1f"}},
   {key = "UpArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x44\x1f"}},
   {key = "UpArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x45\x1f"}},
   {key = "UpArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x46\x1f"}},
   {key = "DownArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x24\x1f"}},
   {key = "DownArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x25\x1f"}},
   {key = "DownArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x26\x1f"}},
   {key = "LeftArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x64\x1f"}},
   {key = "LeftArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x65\x1f"}},
   {key = "LeftArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x66\x1f"}},
   {key = "RightArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x44\x1f"}},
   {key = "RightArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x45\x1f"}},
   {key = "RightArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x46\x1f"}},
   {key = "Home", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x44\x1f"}},
   {key = "Home", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x45\x1f"}},
   {key = "Home", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x46\x1f"}},
   {key = "End", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x24\x1f"}},
   {key = "End", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x25\x1f"}},
   {key = "End", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x26\x1f"}},
   {key = "PageUp", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x58\x61\x1f"}},
   {key = "PageUp", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x64\x1f"}},
   {key = "PageUp", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x65\x1f"}},
   {key = "PageUp", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x66\x1f"}},
   {key = "PageDown", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x59\x41\x1f"}},
   {key = "PageDown", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x44\x1f"}},
   {key = "PageDown", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x45\x1f"}},
   {key = "PageDown", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x46\x1f"}},
}

-- Send complex key combinations to terminal emacs via term-keys.el
config.enable_kitty_keyboard = true

-- WSL
config.default_domain = "WSL:Ubuntu"

return config
