alias s="sudo"

alias au="sudo apt update"
alias aU="sudo apt upgrade"

alias l="ls -lh"
alias e="exa -l"
alias ea="exa -la"
alias et="exa -T"

alias wn="watch --interval 1 nvidia-smi"

alias g="git"
alias gst="git status"
alias ga="git add"
alias gb="git branch"
alias gco="git checkout"
alias gc="git commit"
alias gca="git commit --amend"
alias gd="git diff"
alias gdc="git diff --cached"
alias gl="git log"
alias gls="git log --stat"
alias grs="git reset"
alias grsp="git reset --soft HEAD^"
alias grsh="git reset HEAD"
alias gcl="git clone"
alias grm="git remote"
alias gf="git fetch"
alias gP="git push"
alias gp="git pull"
alias gm="git merge"
alias gcp="git cherry-pick"
alias gcpc="git cherry-pick --continue"
alias gcpa="git cherry-pick --abort"
alias grb="git rebase"
alias grbi="git rebase --interactive"
alias grbc="git rebase --continue"
alias grba="git rebase --abort"
alias grbs="git rebase --skip"

alias pe="pyenv"
alias pev="pyenv version"
alias pevs="pyenv versions"
alias pei="pyenv install"
alias pel="pyenv local"
alias pes="pyenv shell"

alias ipy="ipython"
alias lab="jupyter lab"

alias jl="julia"
