(source org)
(source gnu)
(source melpa)

;; Package configuration
(depends-on "use-package")

;; Key bindings
(depends-on "free-keys")

;; Libaries
(depends-on "dash")
(depends-on "s")

;; Planning
(depends-on "org-plus-contrib")
(depends-on "org-bullets")

;; Load PATH from shell, even when emacs is not started from one
(depends-on "exec-path-from-shell")

;; General editing
(depends-on "avy")
(depends-on "ace-window")
(depends-on "multiple-cursors")
(depends-on "smartparens")
(depends-on "expand-region")
(depends-on "wrap-region")
(depends-on "centimacro")
(depends-on "visual-regexp")
(depends-on "key-chord")
(depends-on "hydra")

;; Convenience
(depends-on "dictcc")

;; UI
(depends-on "color-theme")
(depends-on "material-theme")
(depends-on "smart-mode-line")
(depends-on "rainbow-delimiters")
(depends-on "shackle")
(depends-on "rainbow-mode")
(depends-on "highlight-symbol")
(depends-on "discover-my-major")

;; Snippets
(depends-on "yasnippet")

;; Autocomplete
(depends-on "company")

;; VCS
(depends-on "magit")
(depends-on "git-timemachine")

;; Syntax checking
(depends-on "flycheck")

;; Searching
(depends-on "swiper")
(depends-on "ivy")
(depends-on "counsel")
(depends-on "projectile")
(depends-on "flx")

;; Markdown
(depends-on "markdown-mode")

;; Emacs Lisp
(depends-on "macrostep")

;; C/C++
(depends-on "cmake-mode")
(depends-on "google-c-style")
(depends-on "irony")
(depends-on "irony-eldoc")
(depends-on "company-irony")
(depends-on "company-irony-c-headers")
(depends-on "clang-format")

;; Haskell
(depends-on "haskell-mode")
(depends-on "shm")
(depends-on "ghc")
(depends-on "ghci-completion")

;; Clojure
(depends-on "clojure-mode")
(depends-on "cider")

;; Python
(depends-on "pyenv-mode")
(depends-on "anaconda-mode")
(depends-on "company-anaconda")

;; Javascript
(depends-on "js2-mode")
(depends-on "js2-refactor")

;; Lua
(depends-on "lua-mode")

;; Rust
(depends-on "rust-mode")

;; LaTeX
(depends-on "auctex")

;; Markup Languages
(depends-on "yaml-mode")
